TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'JohannesSteu.Bootstrap.GridSystem': TRUE
    nodeTypes:
      groups:
        grid:
          position: '150'
          label: 'Bootstrap Grids'

JohannesSteu:
  Bootstrap:
    GridSystem:
      rowClassName: 'row'
      collClassName: 'col'
      breakpointClassNames:
        xs: 'col-xs-'
        sm: 'col-sm-'
        md: 'col-md-'
        lg: 'col-lg-'
      Layouts:
        '100-100':
          'col-1': '12'
          'col-2': '12'
        '50-50':
          'col-1': '6'
          'col-2': '6'
        '75-25':
          'col-1': '9'
          'col-2': '3'
        '25-75':
          'col-1': '3'
          'col-2': '9'
        '66-33':
          'col-1': '8'
          'col-2': '4'
        '33-66':
          'col-1': '4'
          'col-2': '8'
        '20-80':
          'col-1': '2'
          'col-2': '10'
        '80-20':
          'col-1': '10'
          'col-2': '2'
        '33-33-33':
          'col-1': '4'
          'col-2': '4'
          'col-3': '4'
        '25-50-25':
          'col-1': '3'
          'col-2': '6'
          'col-3': '3'
        '100-100-100':
          'col-1': '12'
          'col-2': '12'
          'col-3': '12'
        '25-25-25-25':
          'col-1': '3'
          'col-2': '3'
          'col-3': '3'
          'col-4': '3'
        '50-50-50-50':
          'col-1': '6'
          'col-2': '6'
          'col-3': '6'
          'col-4': '6'
        '100-100-100-100':
          'col-1': '12'
          'col-2': '12'
          'col-3': '12'
          'col-4': '12'
